Update russian localisation
Avdan-OS/Website pull request #202
Opened 2022-07-17 16:50 UTC by minegame2021

2022-07-17 16:52 UTC, LazyCat2 commented on src/public/assets/lang/ru.yaml
> +your dock can do more than ever. it's your ultimate manager to get you organised.: Док-панель может иметь больше фичей чем когда либо. Она поможет тебе быть более организованным .
please, fix spase before dot

2022-07-17 17:14 UTC, xAvatar6969 requested changes

2022-07-17 17:14 UTC, xAvatar6969 commented on src/public/assets/lang/ru.yaml
> +your pc but even better!: Ваш ПК, но ещё лучше.
There should be a "!", not a "."

2022-07-22 21:54 UTC, AZProductions commented
Any updates to this pr @minegame2021 ? Or should we close it?

2022-07-22 22:59 UTC, froxcey commented
I will start reviewing after you address the changes requested, or just tell me if you think this is good already

2022-07-29 10:01 UTC, froxcey commented
I guess I will edit this PR myself later if no one want to take care of this.

2022-07-30 09:06 UTC, froxcey approved these changes
I made the changes as requested. I will merge this tomorrow so people can have time to review.

2022-07-30 16:52 UTC, AZProductions reviewed
LGTM

2022-07-31 03:43 UTC, froxcey commented
Alr merging now

2022-07-31 03:43 UTC, merged