French Translation Patch from Nickeldon
Avdan-OS/Website pull request #349
Opened 2022-12-19 00:12 UTC by Froxcey

A big thank you to @Nickeldon for the translation, looks good to me. I will be leaving this up for 2 days for review before merging. 

![vibe](https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif)

2022-12-19 13:48 UTC, Sammy99jsp approved these changes
LGTM!

2022-12-19 21:09 UTC, Golem642 commented on src/public/assets/lang/fr_FR.yaml
> +overview: Aperçu rapide
Voudrait plutôt dire "quick overview" mais ok ¯\_(ツ)_/¯

2022-12-19 21:20 UTC, Golem642 requested changes
Quelques fautes d'orthographe, tirets, et changements à revoir avant de merger

Some changes needed concerning orthograph, hyphens to add, and other stuff before merging

2022-12-19 21:20 UTC, Golem642 commented on src/public/assets/lang/fr_FR.yaml
> +features: Fonctionnalités et Caractéristiques
Même chose, ça rajoute juste des mots et là sachant que c'est pour la barre de menu je suis pas trop d'accord, autant rester court

2022-12-19 21:20 UTC, Golem642 commented on src/public/assets/lang/fr_FR.yaml
> +brand new launch menu: Toute nouvelle intérface de démarrage
interface sans é stp merci

2022-12-20 03:39 UTC, MrSerge01 commented
OUI OUI

2022-12-20 07:44 UTC, Nickeldon commented
Hi !
Ou salutations

Je corrigerais mes fautes de frappes dès aujourd'hui.

Cordialement

On Mon., Dec. 19, 2022, 16:20 Golem64 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Quelques fautes d'orthographe, tirets, et changements à revoir avant de
> merger
>
> Some changes needed concerning orthograph, hyphens to add, and other stuff
> before merging
> ------------------------------
>
> In src/public/assets/lang/fr_FR.yaml
> <https://github.com/Avdan-OS/Website/pull/349#discussion_r1052640501>:
>
> >  home: Accueil
>
> -features: Fonctionnalités
>
> +features: Fonctionnalités et Caractéristiques
>
>
> Même chose, ça rajoute juste des mots et là sachant que c'est pour la
> barre de menu je suis pas trop d'accord, autant rester court
> ------------------------------
>
> In src/public/assets/lang/fr_FR.yaml
> <https://github.com/Avdan-OS/Website/pull/349#discussion_r1052641485>:
>
> >  watch on youtube: regarder sur youtube
>
>  familiar dock, ultimate form: Dock familier, forme ultime
>
> -everyone knows dock/task bar. we got a brand new dock, with more features than ever before.: Tout le monde connais le dock/la barre des tâches. Nous en avons un tout nouveau, avec encore plus de fonctionnalités que jamais auparavant.
>
> -brand new launch menu: Tout nouveau menu de démarrage
>
> +everyone knows dock/task bar. we got a brand new dock, with more features than ever before.: Tout le monde reconnais le dock/la barre des tâches. Nous l'avons repensé, avec encore plus de fonctionnalités que jamais auparavant.
>
> +brand new launch menu: Toute nouvelle intérface de démarrage
>
>
> interface sans é stp merci
> ------------------------------
>
> In src/public/assets/lang/fr_FR.yaml
> <https://github.com/Avdan-OS/Website/pull/349#discussion_r1052642687>:
>
> >  # "try in your browser" is in index.tsx section
>
>  # "open demo" is in features-beta.tsx section
>
>  for most people: Pour la plupart des personnes
>
>  for pi, pine, and mac: Pour pi, pine, et mac
>
>  download: Télécharger
>
>  web preview: Prévisualisation web
>
> -you're about to visit the web demo version of avdanos, which is only a proof of concept. trying the live system is strongly recommended to getting the full experience from the operating system.: Vous êtes sur le point de visiter la démo web de AvdanOS, qui n'est qu'un preuve de concept. Essayer la version live du système est fortement recommendée pour obtenir une expérience complète de l'OS.
>
> -live system is currently not available because the system is still under development: la version live du système n'est actuellement pas disponible car le système est toujours en cours de développement
>
> -yes, take me there: Oui, amenez moi là-bas
>
> +you're about to visit the web demo version of avdanos, which is only a proof of concept. trying the live system is strongly recommended to getting the full experience from the operating system.: Vous êtes sur le point de visiter la démo web de AvdanOS, qui n'est qu'une preuve du concept. La version live du système est recommendée afin d'obtenir une expérience complète de l'OS.
>
> +live system is currently not available because the system is still under development: la version live du système est actuellement indisponible, car le système est toujours en cours de développement
>
> +yes, take me there: Oui, enmenez moi là-bas
>
>
> faute de frappe, à corriger : emmenez-moi
> ------------------------------
>
> In src/public/assets/lang/fr_FR.yaml
> <https://github.com/Avdan-OS/Website/pull/349#discussion_r1052643186>:
>
> >  rotate your device: tournez votre appareil
>
> -your screen is too small to display this page. please rotate to landscape view or use desktop.: votre largeur d'écran est trop petite pour pouvoir afficher le contenu de cette page. Veuillez tourner votre appareil en mode paysage ou utiliser un ordinateur.
>
> +your screen is too small to display this page. please rotate to landscape view or use desktop.: la larrgeur de votre écran est trop petite pour pouvoir afficher le contenu de cette page. Veuillez tourner votre appareil en mode paysage ou utiliser un écran de plus grande taille.
>
>
> double r
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Avdan-OS/Website/pull/349#pullrequestreview-1223538284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMDAKSDISYDDLR263UV7VALWODGR7ANCNFSM6AAAAAATCZI2MA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-20 18:54 UTC, AZProductions commented
Excellent travail, continuez comme ça!

2022-12-22 13:29 UTC, Golem642 approved these changes
Much better, LGTM

2023-01-27 01:50 UTC, merged